"""empty message

Revision ID: 067f13e422dd
Revises: bb89d776e165
Create Date: 2024-05-18 19:43:19.297759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '067f13e422dd'
down_revision = 'bb89d776e165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('room_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('room_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
