"""Add gender to Room and Student

Revision ID: bb89d776e165
Revises: 1c1235b0d994
Create Date: 2024-05-18 10:23:26.720597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb89d776e165'
down_revision = '1c1235b0d994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Додавання колонки 'gender' до 'room' як NULL-допустима, а потім встановлення NOT NULL
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
    # Необхідно заповнити колонку 'gender' усім записам у 'room' перед зміною на NOT NULL
    op.execute("UPDATE room SET gender = 'male'")  # або 'female', в залежності від вашого контексту
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('gender', existing_type=sa.String(length=10), nullable=False)

    # Додавання колонки 'gender' до 'student' як NULL-допустима, а потім встановлення NOT NULL
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
    # Необхідно заповнити колонку 'gender' усім записам у 'student' перед зміною на NOT NULL
    op.execute("UPDATE student SET gender = 'male'")  # або 'female', в залежності від вашого контексту
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('gender', existing_type=sa.String(length=10), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('gender')

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
